name: Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  trigger:
    name: Trigger
    runs-on: ubuntu-latest

    steps:
      - name: Triggeer
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: Somfic/docs-site
          workflow: Deploy
          token: ${{ secrets.PAT_TOKEN }}
