name: Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  trigger:
    name: Trigger
    runs-on: ubuntu-latest

    steps:
      - name: Trigger site workflow
        run: |
          curl --request POST --url 'https://api.github.com/repos/Somfic/docs-site/dispatches' --header 'authorization: Bearer ${{secrets.PAT_TOKEN}}' --data '{"event_type":"hello"}'
